# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: cocainate
before:
  hooks:
    - make completion manual
builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    ldflags:
      - -X 'github.com/AppleGamer22/{{.ProjectName}}/commands.Version={{.Version}}'
      - -X 'github.com/AppleGamer22/{{.ProjectName}}/commands.Hash={{.FullCommit}}'
  - id: mac
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/{{.ProjectName}}/commands.Version={{.Version}}'
      - -X 'github.com/AppleGamer22/{{.ProjectName}}/commands.Hash={{.FullCommit}}'
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/{{.ProjectName}}/commands.Version={{.Version}}'
      - -X 'github.com/AppleGamer22/{{.ProjectName}}/commands.Hash={{.FullCommit}}'
archives:
  - id: unix
    builds:
    - linux
    - mac
    name_template: >-
      {{- .ProjectName}}_
      {{- .Version}}_
      {{- if eq .Os "darwin"}}mac{{else}}
        {{- .Os}}
      {{- end}}_
      {{- .Arch}}
    files:
      - "{{.ProjectName}}.bash"
      - "{{.ProjectName}}.fish"
      - "{{.ProjectName}}.zsh"
      - "{{.ProjectName}}.1"
  - id: windows
    builds:
      - windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - "{{.ProjectName}}.ps1"
      - "{{.ProjectName}}.1"
nfpms:
  - vendor: AppleGamer22
    maintainer: Omri Bornstein <omribor@gmail.com>
    homepage: https://github.com/AppleGamer22/{{.ProjectName}}
    license: GPL-3.0
    description: Cross-platform caffeinate alternative.
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    builds:
      - linux
    dependencies:
      - dbus
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    contents:
      - src: "{{.ProjectName}}.1"
        dst: /usr/share/man/man1/{{.ProjectName}}.1
      - src: "{{.ProjectName}}.bash"
        dst: /usr/share/bash-completion/completions/{{.ProjectName}}
      - src: "{{.ProjectName}}.fish"
        dst: /usr/share/fish/completions/{{.ProjectName}}.fish
      - src: "{{.ProjectName}}.zsh"
        dst: /usr/share/zsh/site-functions/_{{.ProjectName}}
changelog:
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - typo
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
release:
  github:
    owner: AppleGamer22
    name: "{{.ProjectName}}"
  discussion_category_name: General
  footer: |
    ## Installation
    ### Nix Flakes
    ```nix
    {
      inputs = {
        # or your preferred NixOS channel
        nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
        applegamer22.url = "github:AppleGamer22/nur";
      };
      outputs = { nixpkgs }: {
        nixosConfigurations.nixos = nixpkgs.lib.nixosSystem {
          specialArgs = {
            pkgs = import nixpkgs {
              # ...
              overlays = [
                (final: prev: {
                  # ...
                  ag22 = applegamer22.packages."<your_system>";
                })
              ];
            };
          };
          modules = [
            # or in a separate Nix file
            ({ pkgs, ... }: {
              programs.nix-ld.enable = true;
              environment.systemPackages = with pkgs; [
                ag22.{{.ProjectName}}
              ];
            })
            # ...
          ];
        };
      };
    }
    ```
    ### Arch Linux Distributions
    * [`yay`](https://github.com/Jguer/yay):
    ```bash
    yay -S {{.ProjectName}}-bin
    ```
    * [`paru`](https://github.com/morganamilo/paru):
    ```bash
    paru -S {{.ProjectName}}-bin
    ```

    ### macOS
    * [Homebrew Tap](https://github.com/AppleGamer22/homebrew-tap):
    ```bash
    brew install AppleGamer22/tap/{{.ProjectName}}
    ```
  prerelease: auto
nix:
  - repository:
      owner: AppleGamer22
      name: nur
      token: "{{.Env.TAP_GITHUB_TOKEN}}"
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
    homepage: https://github.com/AppleGamer22/{{.ProjectName}}
    description: Cross-platform caffeinate alternative.
    license: gpl3Only
    ids:
      - unix
    install: |
      mkdir -p $out/bin
      cp -vr ./{{.ProjectName}} $out/bin/{{.ProjectName}}
      installManPage ./{{.ProjectName}}.1
      installShellCompletion ./{{.ProjectName}}.*sh
brews:
  - repository:
      owner: AppleGamer22
      name: homebrew-tap
      token: "{{.Env.TAP_GITHUB_TOKEN}}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
    homepage: https://github.com/AppleGamer22/{{.ProjectName}}
    description: Cross-platform caffeinate alternative.
    license: GPL-3.0
    install: |
      bin.install "{{.ProjectName}}"
      man1.install "{{.ProjectName}}.1"
      bash_completion.install "{{.ProjectName}}.bash" => "{{.ProjectName}}"
      fish_completion.install "{{.ProjectName}}.fish"
      zsh_completion.install "{{.ProjectName}}.zsh" => "_{{.ProjectName}}"
aurs:
  - homepage: https://github.com/AppleGamer22/{{.ProjectName}}
    description: Cross-platform caffeinate alternative.
    license: GPL3
    maintainers:
      - Omri Bornstein <omribor@gmail.com>
    contributors:
      - Omri Bornstein <omribor@gmail.com>
    private_key: "{{.Env.AUR_SSH_PRIVATE_KEY}}"
    git_url: ssh://aur@aur.archlinux.org/{{.ProjectName}}-bin.git
    depends:
      - dbus
    optdepends:
      - bash
      - fish
      - zsh
    package: |
      install -Dm755 {{.ProjectName}} "${pkgdir}/usr/bin/{{.ProjectName}}"
      install -Dm644 {{.ProjectName}}.1 "${pkgdir}/usr/share/man/man1/{{.ProjectName}}.1"
      install -Dm644 {{.ProjectName}}.bash "${pkgdir}/usr/share/bash-completion/completions/{{.ProjectName}}"
      install -Dm644 {{.ProjectName}}.fish "${pkgdir}/usr/share/fish/vendor_completions.d/{{.ProjectName}}.fish"
      install -Dm644 {{.ProjectName}}.zsh "${pkgdir}/usr/share/zsh/site-functions/_{{.ProjectName}}"
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
sboms:
  - artifacts: archive