# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: cocainate
before:
  hooks:
    - sh -c "go run . completion bash > cocainate.bash"
    - sh -c "go run . completion fish > cocainate.fish"
    - sh -c "go run . completion zsh > cocainate.zsh"
    - sh -c "go run . completion powershell > cocainate.ps1"
builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    ldflags:
      - -X 'github.com/AppleGamer22/cocainate/cmd.Version={{ .Version }}'
      - -X 'github.com/AppleGamer22/cocainate/cmd.Hash={{ .FullCommit }}'
  - id: mac
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/cocainate/cmd.Version={{ .Version }}'
      - -X 'github.com/AppleGamer22/cocainate/cmd.Hash={{ .FullCommit }}'
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/cocainate/cmd.Version={{ .Version }}'
      - -X 'github.com/AppleGamer22/cocainate/cmd.Hash={{ .FullCommit }}'
archives:
  - builds:
    - linux
    - mac
    - windows
    replacements:
      darwin: mac
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - cocainate.bash
      - cocainate.fish
      - cocainate.zsh
      - cocainate.ps1
      - cocainate.1
nfpms:
  - package_name: cocainate
    vendor: AppleGamer22
    maintainer: Omri Bornstein <omribor@gmail.com>
    homepage: https://github.com/AppleGamer22/cocainate
    license: GPL-3.0
    description: Cross-platform caffeinate alternative.
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - linux
    dependencies:
      - dbus
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: cocainate.1
        dst: /usr/share/man/man1/cocainate.1
      - src: cocainate.bash
        dst: /usr/share/bash-completion/completions/cocainate
      - src: cocainate.fish
        dst: /usr/share/fish/completions/cocainate.fish
      - src: cocainate.zsh
        dst: /usr/share/zsh/site-functions/_cocainate
release:
  github:
    owner: AppleGamer22
    name: cocainate
  discussion_category_name: General
  prerelease: auto
aurs:
  - homepage: https://github.com/AppleGamer22/cocainate
    description: Cross-platform caffeinate alternative.
    license: GPL3
    maintainers:
      - Omri Bornstein <omribor@gmail.com>
    contributors:
      - Omri Bornstein <omribor@gmail.com>
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/cocainate-bin.git
    depends:
      - dbus
    optdepends:
      - bash
      - fish
      - zsh
    package: |
      install -Dm755 cocainate "${pkgdir}/usr/bin/cocainate"
      install -Dm644 cocainate.1 "${pkgdir}/usr/share/man/man1/cocainate.1"
      install -Dm644 cocainate.bash "${pkgdir}/usr/share/bash-completion/completions/cocainate"
      install -Dm644 cocainate.fish "${pkgdir}/usr/share/fish/vendor_completions.d/cocainate.fish"
      install -Dm644 cocainate.zsh "${pkgdir}/usr/share/zsh/site-functions/_cocainate"
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
brews:
  - tap:
      owner: AppleGamer22
      name: homebrew-cocainate
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
    homepage: https://github.com/AppleGamer22/cocainate
    description: Cross-platform caffeinate alternative.
    license: GPL-3.0
    install: |
      bin.install "cocainate"
      man1.install "cocainate.1"
      bash_completion.install "cocainate.bash" => "cocainate"
      fish_completion.install "cocainate.fish"
      zsh_completion.install "cocainate.zsh" => "_cocainate"