# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: cocainate
before:
  hooks:
    - env VERSION=${$(git describe --tags --abbrev=0)/v}
    - env GORELEASER_CURRENT_TAG=$VERSION
    - env HASH=$(shell git rev-list -1 HEAD)
    - go run . completion bash > cocainate.bash
    - go run . completion fish > cocainate.fish
    - go run . completion zsh > cocainate.zsh
    - go run . completion powershell > cocainate.ps1
builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    ldflags:
      - -X 'github.com/AppleGamer22/cocainate/cmd.Version={{.Env.VERSION}}'
      - -X 'github.com/AppleGamer22/cocainate/cmd.Hash={{.Env.HASH}}'
  - id: mac_windows
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/cocainate/cmd.Version={{.Env.VERSION}}'
      - -X 'github.com/AppleGamer22/cocainate/cmd.Hash={{.Env.HASH}}'
archives:
  - builds:
    - linux
    - mac_windows
    replacements:
      darwin: mac
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - cocainate.bash
      - cocainate.fish
      - cocainate.zsh
      - cocainate.ps1
      - cocainate.1
nfpms:
  - package_name: cocainate
    vendor: AppleGamer22
    maintainer: Omri Bornstein <omribor@gmail.com>
    homepage: https://github.com/AppleGamer22/cocainate
    license: GPL-3.0
    description: Cross-platform caffeinate alternative.
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - linux
    dependencies:
      - dbus
    formats:
      - apk
      - deb
      - rpm
release:
  github:
    owner: AppleGamer22
    name: cocainate
  prerelease: auto
aurs:
  - homepage: https://github.com/AppleGamer22/cocainate
    description: Cross-platform caffeinate alternative.
    license: GPL3
    maintainers:
      - Omri Bornstein <omribor@gmail.com>
    contributors:
      - Omri Bornstein <omribor@gmail.com>
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/cocainate-bin.git
    depends:
      - dbus
    optdepends:
      - bash
      - fish
      - zsh
    package: |
      install -Dm755 cocainate "${pkgdir}/usr/bin/cocainate"
      install -Dm644 cocainate.1 "${pkgdir}/usr/share/man/man1/cocainate.1"
      install -Dm644 cocainate.bash "${pkgdir}/usr/share/bash-completion/completions/cocainate"
      install -Dm644 cocainate.fish "${pkgdir}/usr/share/fish/vendor_completions.d/cocainate.fish"
      install -Dm644 cocainate.zsh "${pkgdir}/usr/share/zsh/site-functions/_cocainate"
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
brews:
  - tap:
      owner: AppleGamer22
      name: homebrew-cocainate
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
    homepage: https://github.com/AppleGamer22/cocainate
    description: Cross-platform caffeinate alternative.
    license: GPL-3.0
    install: |
      bin.install "cocainate"
      man1.install "cocainate.1"
      bash_completion.install "cocainate.bash" => "cocainate"
      fish_completion.install "cocainate.fish"
      zsh_completion.install "cocainate.zsh" => "_cocainate"