.TH "COCAINATE" "1" "DATE" "cocainate vVERSION" "cocainate Manual"
.nh
.ad l
.SH NAME
\fIcocainate\fR \- Cross\-platform caffeinate alternative

.SH SYNOPSIS
\fIcocainate\fR [options]
.sp
\fIcocainate\fR version [options]
.sp
\fIcocainate\fR

.SH DESCRIPTION
cocainate is a command-line utility that communicates with OS-level APIs
to keep the screen awake.

.SH COCAINATE OPTIONS
.B \-d, \-\-duration
Accepts a duration for timed screensaver inhibitation. If the
.B \-p
flag is provided, the
.B \-d
flag's value is used as process polling interval.

Acceptable units include:

.IP \[bu] 2
nanoseconds:
.BI ns
.IP \[bu]
microseconds:
.BI us
or
.BI µs
.IP \[bu]
milliseconds:
.BI ms
.IP \[bu]
seconds:
.BI s
.IP \[bu]
minutes:
.BI m
.IP \[bu]
hours:
.BI h

.B \-p, \-\-pid
Accepts a running process ID (PID) such that the screensaver inhibitation will terminate as soon as the provided process has termination. The delay between the termination of the provided process and the termination of screensaver inhibitation depends on the
.B \-d
flag (which must be provided).

.B \-h, \-\-help
Displays documentation.

.SH VERSION OPTIONS
.B \-v, \-\-verbose
Displays \fIcocainate\fR's version

.SH EXAMPLES
.TP
\fIcocainate\fR
Keep the screen awake until stoped

.TP
\fIcocainate\fR -d 10h
Keep the screen awake for 10 hours
.TP
\fIcocainate\fR -d 1h10m10s
Keep the screen awake for 1 hour, 10 minutes and 10 seconds
.TP
\fIcocainate\fR -d 1us
Keep the screen awake for 1 microsecond
.TP
\fIcocainate\fR -p 1234 -d 5s
Keep the screen awake while process 1234 runs and check every 5 seconds that process 1234 still runs.

.SH BUGS
Please report bugs to our GitHub page https://github.com/AppleGamer22/cocainate/issues

.SH AUTHORS
Omri Bornstein <omribor@gmail.com>

.SH COPYRIGHT
\fIcocainate\fR is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3, or (at your option) any later version.

\fIcocainate\fR is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.