package ps

var Blocklist = []string{
	"systemd",
	"sddm-helper",
	"pulseaudio",
	"xdg-document-portal",
	"gdm-session-worker",
	"gdm-x-session",
	"gnome-session-binary",
	"dbus-daemon",
	"at-spi-bus-launcher",
	"ibus-daemon",
	"gnome-shell",
	"ibus-memconf",
	"ibus-daemon",
	"ibus-extension-gtk3",
	"ibus-daemon",
	"gvfsd-trash",
	"gvfsd",
	"evolution-alarm-notify",
	"gnome-session-binary",
	"ibus-engine-simple",
	"ibus-daemon",
	"gsd-disk-utility-notify",
	"gnome-session-binary",
	"plasma-browser-integration-host",
	"nacl_helper",
}
