name: Publish to Arch User Repository
on:
  workflow_run:
    workflows: ["Release to GitHub"]
    types:
      - completed
jobs:
  aur_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v2.3.4
      # - name: Get version
      #   id: get_version
      #   run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      - name: Publish AUR Package
        uses: ATiltedTree/create-aur-release@v1.0.4
        with:
          package_name: cocainate-bin
          commit_username: "Omri Bornstein"
          commit_email: omribor@gmail.com
          ssh_private_key: ${{secrets.AUR_SSH_PRIVATE_KEY}}