name: Publish Binaries
on:
  release:
    types: [published]
jobs:
  publish-go-bin:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v2.3.4
      - name: Set-up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.17.5"
      - name: Build
        run: make build
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/cocainate_${{steps.get_version.outputs.VERSION}}_linux_amd64
            ./bin/cocainate_${{steps.get_version.outputs.VERSION}}_linux_arm64
            ./bin/cocainate_${{steps.get_version.outputs.VERSION}}_linux_riscv64
            ./bin/cocainate_${{steps.get_version.outputs.VERSION}}_mac_amd64
            ./bin/cocainate_${{steps.get_version.outputs.VERSION}}_mac_arm64
            ./bin/cocainate_${{steps.get_version.outputs.VERSION}}_windows_amd64.exe
            ./bin/cocainate_${{steps.get_version.outputs.VERSION}}_windows_arm64.exe
