name: Update Documentation
on:
  push:
    tags: ['v*']
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set-up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: stable
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/v}
      - name: Publish Documentation
        run: GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/AppleGamer22/cocainate@v${{steps.get_version.outputs.VERSION}}
