name: Update Documentation
on:
  push:
    tags: ['v*']
jobs:
  github_release:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v2.3.4
      - name: Set-up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.17.5"
      - name: Build & Package
        run: make package
      - name: Get version
        id: get_version
        run: |
          version=GITHUB_REF##*/
          echo ::set-output name=VERSION::${version:1}
      - name: Publish Documentation
        run: GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/AppleGamer22/cocainate@v${{steps.get_version.outputs.VERSION}}